---

- hosts: webservers
  
  tasks:

  - name: stop apache
    service:
      name: httpd
      state: stopped

  - name: remove the index file
    file:
      path: /var/www/html/index.html
      state: absent


  - name: uninstall apache
    yum:
      name: httpd
      state: absent

...
